'developer-role', should have all(*) permissions for services in development namespace

'developer-role', should have all permissions(*) for persistentvolumeclaims in development namespace

'developer-role', should have all(*) permissions for pods in development namespace


kubectl create role developer-role --verb=get --verb=list --verb=watch --resource=pods

kubectl create role pod-reader --verb=get --resource=pods --resource-name=readablepod --resource-name=anotherpod


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: developer-role 
rules:
- apiGroups: [""]
  resources: ["services", "pods", "persistentvolumeclaims" ]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-role
  namespace: default
subjects:
- kind: User
  name: martin 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: developer-role 
  apiGroup: rbac.authorization.k8s.io